### ISSUE TITLE
Facelift (Redesign) Epic

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/dbs-front#290]
General Search Results page:

- [ ] General Search Suggestions

- [ ] Move Family Tree tab from main toolbar to results tabs

- [ ] Add Paging (Separately for CJH, Europeana, any future collaborators)

- [ ] Add Sorting 

- [ ] Remove Home (Wizard)

- [ ] Add "Results per page" selector

- [ ] Change item type indicator on cards from animated strip to red icon before title

Item Page:

- [ ] Add Results from elsewhere on the internet to bottom of item page

- [ ] Hide long texts on item page behind "Continue reading" button

Header

- [ ] Selected item indicator needs to have a triangular bottom

- [ ] Add Upload button
